# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      # docker compose pull
      gp info
      node -e "console.log( require('os').version() )"
      url=$(node -e "console.log( require('process').env.GITPOD_WORKSPACE_URL )") && echo $url
      (gp ports list 2> /dev/null) || true
  - command: |
      # docker compose up
      echo -e "\033[1;44m Gitpod Workspace \033[0m"
      echo -e "\033[0;33m by Alerox, 2022 \033[0m"
      echo

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Node-RED
    description: Flow programming
    port: 1880
    onOpen: notify # open-browser # open-preview
    visibility: public
