# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: help
    init: |
      # A list of useful commands
      echo -e "\033[1;32m SYSTEM \033[0m"
      uname -nrpv
      echo -e "\033[1;33m PORTS \033[0m"
      ss -tunlp
      echo -e "\033[1;34m CPU \033[0m"
      cat /proc/cpuinfo|grep name
      echo -e "\033[1;35m RAM \033[0m"
      free -m
      echo -e "\033[1;36m DISKS \033[0m"
      df -h
      echo -e "\033[1;31m MISC \033[0m"
      echo " PROCESSES "
      ps aux # acrux
      echo " DOCKER "
      docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      echo " GITPOD "
      gp info
      (gp ports list 2> /dev/null) || true
      echo " NODE.JS "
      node -e "console.log( require('os').version() )"
      url=$(node -e "console.log( require('process').env.GITPOD_WORKSPACE_URL )") && echo $url
  - name: workspace
    command: |
      clear
      echo -e "\033[1;44m Gitpod Workspace \033[0m"
      echo -e "\033[0;33m by Alerox, 2022 \033[0m"
      echo

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Node-RED
    description: Flow programming
    port: 1880
    onOpen: notify # open-browser # open-preview
    visibility: public
