tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
  - port: 1026
    onOpen: ignore
  - port: 1880
    onOpen: open-browser
  - port: 3005
    onOpen: open-preview
  - port: 8745
    onOpen: ignore
  - port: 27127
    onOpen: ignore

