# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      # docker compose pull
      echo -e "\033[1;44m Gitpod Workspace \033[0m"
      echo -e "\033[0;33m by Alerox, 2022 \033[0m"
      node -e "console.log( require('os').version() )"
      url=$(node -e "console.log( require('process').env.GITPOD_WORKSPACE_URL )") && echo $url
    command: |
      # docker compose up
      (gp ports list 2> /dev/null) || true
      gp info

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Node-RED
    port: 1880
    onOpen: open-preview # open-browser
    visibility: public
  - name: Orion
    description: FIWARE Context Broker
    port: 1026
    onOpen: notify
  - name: Wilma
    description: FIWARE PEP Proxy
    port: 1027
    onOpen: ignore
  - name: Keyrock
    description: FIWARE IdM
    port: 3005
    onOpen: ignore
  - name: KeyCloak
    port: 8080
    onOpen: ignore
  - name: MQTT
    port: 1883
    onOpen: ignore
    visibility: public
  - name: MQTT over Websocket
    port: 9001
    onOpen: ignore
    visibility: public
  - name: Grafana
    port: 3000
    onOpen: ignore
  - name: Ganache
    port: 7545
    onOpen: ignore
  - name: Hardhat
    port: 8545
    onOpen: ignore
  - name: MySQL
    port: 3306
    onOpen: ignore
  - name: Influx
    port: 8086
    onOpen: ignore
  - name: Mongo
    port: 27017
    onOpen: ignore
  - name: MongoExpress
    port: 8081
    onOpen: ignore
